### ISSUE TITLE
Moderated Mediation - Results Table with indirect, direct, total effects --> swapped lines?

### ISSUE THREAD

**Issue by denisedoerfel** [jamovi-amm/jamm#11]
Hello, 
I am using Jamovi-amm, version 1.6.23.0 to analyse the following: x1, x2 as predictors m as mediator, y as outcome (there are additional 3 covariates, I will neglect here). My model is y ~ m + x1 + x2 + x1*x2 (+ additional covariates). x2 was entered via interaction into the mediator model. (not as moderator in the moderator model). 

The results are: 
Direct effecs on outcome: x1 --> not significant, x2 --> significant , interaction --> not sign.
Indirect effects on outcome: x1 --> sign. , x2 --> sign., interaction --> not sign.
Direct effects on mediator: x1 --> sign., x2 --> sign.
So far everything fits, but the total effects puzzle me:
Total effects on outcome:  x1 --> sign., x2 --> not sign. (!), interaction --> sign. (!)

Is it plausible that with a highly significant (<.001) indirect effect of x2 and a slighly significant (p=.044) direct effect of x2 on the outcome the total effect of x2 does not become significant with p =.991?
Is it possible, that in the results table the lines under total effects are swapped and the results of the interaction are in fact the results of x2? 

I'll attach a png with detailed results of my analysis with the acutal labeling of my variables. It's not only a problem of p just not reaching significance, which can be seen in the attached table.  
I have also noticed this in similar analyses with other samples and more predictors and one more interaction.
With SPSS/PROCESS and lavaan in R the results of the total effects and the direct/indirect effects fit.
 
It's not only a problem of p just not reaching significance, which can be seen in the attached table.  
Thanks for looking into this.
Denise
![SimpleModeratedMediation](https://user-images.githubusercontent.com/95695862/148754259-28114932-19b8-4da6-9eb4-216ef2c00174.png)

**Comment by mcfanda** [comment]
Hi, if you are referring to T1_emotional_job_demands when you asked about the plausibility of the results ( highly significant (<.001) indirect effect of x2 and a slighly significant (p=.044) direct effect of x2 on the outcome the total effect of x2 does not become significant with p =.991), the results you posted seem to be correct. The problem is not the significance, but the direction of the effect.

For T1_emotional_job_demands , the indirect effect is -.079, and the direct effect is .079 (both rounded). Since the total effect is the sum of indirect and direct effect, you have Total=-.079+.079=0. Indeed (without rounding), you get -4.36^-4 which is practically 0. 

If you want to be sure, run a regression with all variables excluding the mediator. It should confirm a coefficient for T1_emotional_job_demands close to zero and an associated p-value around >.9.

Please let me know how the test went

**Comment by denisedoerfel** [comment]
Dear Marcello, 
you are absolutely right, I was so stuck that I didn't consider this. The direction of the effects makes sense and has been hypothesized this way. 
The regression showed exactly what you predicted, but only if I also leave out the interaction term. Is this correct?

Thanks a lot!!! 
Denise. 
![image](https://user-images.githubusercontent.com/95695862/148782274-90086576-35e9-4d62-9940-92e8b5e70aeb.png)

**Comment by mcfanda** [comment]
if you center the variables involved in the interaction, you'll get the same results also with the interaction in the model

**Comment by denisedoerfel** [comment]
Ah, I see! Thanks a lot.
