### ISSUE TITLE
different results in jamm and medmod modules

### ISSUE THREAD

**Issue by DrEaiyao** [jamovi-amm/jamm#26]
I conducted a simple mediation in jamovi, and there are different results between jamm and medmod. However, the results in R (no matter using bruceR or jamm package) and medmod are almostly the same. I don't know why jamm in jamovi has a totally different answer.

- jamm in jamovi

![jamm in jamovi](https://github.com/user-attachments/assets/4b1ec374-694c-4cca-9ead-634fc128daa4)

- medmod results

![medmod results](https://github.com/user-attachments/assets/fcfcf2fd-4329-458d-8f25-18a8db6e8004)

- bruceR

![bruceR](https://github.com/user-attachments/assets/63e3bb08-9953-435d-81c9-973b73093cda)

- jamm in R

![jamm in R](https://github.com/user-attachments/assets/d0e0cf48-7e05-45d0-b3e1-b7f386c49ece)

**Comment by DrEaiyao** [comment]
It seems that jamm in jamovi gives twice as many results as the other methods

**Comment by mcfanda** [comment]
I guess your independent variable is a dichotomous variable. If so, the difference in the coefficients is due to the coding of the factor. Coding of factors is arbitrary, so different software use different schemes, but the results are equivalent (bootstrap difference aside), as you can see from the z-tests, that are equivalent across outputs.
Thus, it is crucial here to know how you coded your factor (and if in R you defined it as a factor). When the independent variable is correctly coded, medmod, jamm  (and I guess mediate/bruceR) give the same results.
